scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets: ['api-gateway:3000', 'order-service:3001', 'inventory-service:3002', 'payment-service:3003']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
